/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package br.com.retailsales.commons.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class AvroInvoice extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -3377821906656796491L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AvroInvoice\",\"namespace\":\"br.com.retailsales.commons.avro\",\"fields\":[{\"name\":\"invoiceCode\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Invoice code.\"},{\"name\":\"paymentCode\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Payment code.\"},{\"name\":\"processingDate\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<AvroInvoice> ENCODER =
      new BinaryMessageEncoder<AvroInvoice>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<AvroInvoice> DECODER =
      new BinaryMessageDecoder<AvroInvoice>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<AvroInvoice> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<AvroInvoice> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<AvroInvoice>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this AvroInvoice to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a AvroInvoice from a ByteBuffer. */
  public static AvroInvoice fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Invoice code. */
   private java.lang.String invoiceCode;
  /** Payment code. */
   private java.lang.String paymentCode;
   private org.joda.time.DateTime processingDate;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AvroInvoice() {}

  /**
   * All-args constructor.
   * @param invoiceCode Invoice code.
   * @param paymentCode Payment code.
   * @param processingDate The new value for processingDate
   */
  public AvroInvoice(java.lang.String invoiceCode, java.lang.String paymentCode, org.joda.time.DateTime processingDate) {
    this.invoiceCode = invoiceCode;
    this.paymentCode = paymentCode;
    this.processingDate = processingDate;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return invoiceCode;
    case 1: return paymentCode;
    case 2: return processingDate;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  protected static final org.apache.avro.data.TimeConversions.DateConversion DATE_CONVERSION = new org.apache.avro.data.TimeConversions.DateConversion();
  protected static final org.apache.avro.data.TimeConversions.TimeConversion TIME_CONVERSION = new org.apache.avro.data.TimeConversions.TimeConversion();
  protected static final org.apache.avro.data.TimeConversions.TimestampConversion TIMESTAMP_CONVERSION = new org.apache.avro.data.TimeConversions.TimestampConversion();
  protected static final org.apache.avro.Conversions.DecimalConversion DECIMAL_CONVERSION = new org.apache.avro.Conversions.DecimalConversion();

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      null,
      TIMESTAMP_CONVERSION,
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: invoiceCode = (java.lang.String)value$; break;
    case 1: paymentCode = (java.lang.String)value$; break;
    case 2: processingDate = (org.joda.time.DateTime)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'invoiceCode' field.
   * @return Invoice code.
   */
  public java.lang.String getInvoiceCode() {
    return invoiceCode;
  }

  /**
   * Sets the value of the 'invoiceCode' field.
   * Invoice code.
   * @param value the value to set.
   */
  public void setInvoiceCode(java.lang.String value) {
    this.invoiceCode = value;
  }

  /**
   * Gets the value of the 'paymentCode' field.
   * @return Payment code.
   */
  public java.lang.String getPaymentCode() {
    return paymentCode;
  }

  /**
   * Sets the value of the 'paymentCode' field.
   * Payment code.
   * @param value the value to set.
   */
  public void setPaymentCode(java.lang.String value) {
    this.paymentCode = value;
  }

  /**
   * Gets the value of the 'processingDate' field.
   * @return The value of the 'processingDate' field.
   */
  public org.joda.time.DateTime getProcessingDate() {
    return processingDate;
  }

  /**
   * Sets the value of the 'processingDate' field.
   * @param value the value to set.
   */
  public void setProcessingDate(org.joda.time.DateTime value) {
    this.processingDate = value;
  }

  /**
   * Creates a new AvroInvoice RecordBuilder.
   * @return A new AvroInvoice RecordBuilder
   */
  public static br.com.retailsales.commons.avro.AvroInvoice.Builder newBuilder() {
    return new br.com.retailsales.commons.avro.AvroInvoice.Builder();
  }

  /**
   * Creates a new AvroInvoice RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AvroInvoice RecordBuilder
   */
  public static br.com.retailsales.commons.avro.AvroInvoice.Builder newBuilder(br.com.retailsales.commons.avro.AvroInvoice.Builder other) {
    return new br.com.retailsales.commons.avro.AvroInvoice.Builder(other);
  }

  /**
   * Creates a new AvroInvoice RecordBuilder by copying an existing AvroInvoice instance.
   * @param other The existing instance to copy.
   * @return A new AvroInvoice RecordBuilder
   */
  public static br.com.retailsales.commons.avro.AvroInvoice.Builder newBuilder(br.com.retailsales.commons.avro.AvroInvoice other) {
    return new br.com.retailsales.commons.avro.AvroInvoice.Builder(other);
  }

  /**
   * RecordBuilder for AvroInvoice instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AvroInvoice>
    implements org.apache.avro.data.RecordBuilder<AvroInvoice> {

    /** Invoice code. */
    private java.lang.String invoiceCode;
    /** Payment code. */
    private java.lang.String paymentCode;
    private org.joda.time.DateTime processingDate;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(br.com.retailsales.commons.avro.AvroInvoice.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.invoiceCode)) {
        this.invoiceCode = data().deepCopy(fields()[0].schema(), other.invoiceCode);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.paymentCode)) {
        this.paymentCode = data().deepCopy(fields()[1].schema(), other.paymentCode);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.processingDate)) {
        this.processingDate = data().deepCopy(fields()[2].schema(), other.processingDate);
        fieldSetFlags()[2] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing AvroInvoice instance
     * @param other The existing instance to copy.
     */
    private Builder(br.com.retailsales.commons.avro.AvroInvoice other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.invoiceCode)) {
        this.invoiceCode = data().deepCopy(fields()[0].schema(), other.invoiceCode);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.paymentCode)) {
        this.paymentCode = data().deepCopy(fields()[1].schema(), other.paymentCode);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.processingDate)) {
        this.processingDate = data().deepCopy(fields()[2].schema(), other.processingDate);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'invoiceCode' field.
      * Invoice code.
      * @return The value.
      */
    public java.lang.String getInvoiceCode() {
      return invoiceCode;
    }

    /**
      * Sets the value of the 'invoiceCode' field.
      * Invoice code.
      * @param value The value of 'invoiceCode'.
      * @return This builder.
      */
    public br.com.retailsales.commons.avro.AvroInvoice.Builder setInvoiceCode(java.lang.String value) {
      validate(fields()[0], value);
      this.invoiceCode = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'invoiceCode' field has been set.
      * Invoice code.
      * @return True if the 'invoiceCode' field has been set, false otherwise.
      */
    public boolean hasInvoiceCode() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'invoiceCode' field.
      * Invoice code.
      * @return This builder.
      */
    public br.com.retailsales.commons.avro.AvroInvoice.Builder clearInvoiceCode() {
      invoiceCode = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'paymentCode' field.
      * Payment code.
      * @return The value.
      */
    public java.lang.String getPaymentCode() {
      return paymentCode;
    }

    /**
      * Sets the value of the 'paymentCode' field.
      * Payment code.
      * @param value The value of 'paymentCode'.
      * @return This builder.
      */
    public br.com.retailsales.commons.avro.AvroInvoice.Builder setPaymentCode(java.lang.String value) {
      validate(fields()[1], value);
      this.paymentCode = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'paymentCode' field has been set.
      * Payment code.
      * @return True if the 'paymentCode' field has been set, false otherwise.
      */
    public boolean hasPaymentCode() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'paymentCode' field.
      * Payment code.
      * @return This builder.
      */
    public br.com.retailsales.commons.avro.AvroInvoice.Builder clearPaymentCode() {
      paymentCode = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'processingDate' field.
      * @return The value.
      */
    public org.joda.time.DateTime getProcessingDate() {
      return processingDate;
    }

    /**
      * Sets the value of the 'processingDate' field.
      * @param value The value of 'processingDate'.
      * @return This builder.
      */
    public br.com.retailsales.commons.avro.AvroInvoice.Builder setProcessingDate(org.joda.time.DateTime value) {
      validate(fields()[2], value);
      this.processingDate = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'processingDate' field has been set.
      * @return True if the 'processingDate' field has been set, false otherwise.
      */
    public boolean hasProcessingDate() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'processingDate' field.
      * @return This builder.
      */
    public br.com.retailsales.commons.avro.AvroInvoice.Builder clearProcessingDate() {
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public AvroInvoice build() {
      try {
        AvroInvoice record = new AvroInvoice();
        record.invoiceCode = fieldSetFlags()[0] ? this.invoiceCode : (java.lang.String) defaultValue(fields()[0], record.getConversion(0));
        record.paymentCode = fieldSetFlags()[1] ? this.paymentCode : (java.lang.String) defaultValue(fields()[1], record.getConversion(1));
        record.processingDate = fieldSetFlags()[2] ? this.processingDate : (org.joda.time.DateTime) defaultValue(fields()[2], record.getConversion(2));
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<AvroInvoice>
    WRITER$ = (org.apache.avro.io.DatumWriter<AvroInvoice>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<AvroInvoice>
    READER$ = (org.apache.avro.io.DatumReader<AvroInvoice>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
