/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package br.com.retailsales.commons.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class AvroOrder extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 6336366983644824156L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AvroOrder\",\"namespace\":\"br.com.retailsales.commons.avro\",\"fields\":[{\"name\":\"orderCode\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Order code.\"},{\"name\":\"customerCode\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Customer code ID.\"},{\"name\":\"productList\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"AvroProduct\",\"fields\":[{\"name\":\"productCode\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Product code.\"},{\"name\":\"productPrice\",\"type\":\"double\",\"doc\":\"Product price.\"},{\"name\":\"productAmount\",\"type\":\"int\",\"doc\":\"Product amount.\",\"default\":1}]}},\"doc\":\"Product list.\"},{\"name\":\"processingDate\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<AvroOrder> ENCODER =
      new BinaryMessageEncoder<AvroOrder>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<AvroOrder> DECODER =
      new BinaryMessageDecoder<AvroOrder>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<AvroOrder> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<AvroOrder> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<AvroOrder>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this AvroOrder to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a AvroOrder from a ByteBuffer. */
  public static AvroOrder fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Order code. */
   private java.lang.String orderCode;
  /** Customer code ID. */
   private java.lang.String customerCode;
  /** Product list. */
   private java.util.List<br.com.retailsales.commons.avro.AvroProduct> productList;
   private org.joda.time.DateTime processingDate;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AvroOrder() {}

  /**
   * All-args constructor.
   * @param orderCode Order code.
   * @param customerCode Customer code ID.
   * @param productList Product list.
   * @param processingDate The new value for processingDate
   */
  public AvroOrder(java.lang.String orderCode, java.lang.String customerCode, java.util.List<br.com.retailsales.commons.avro.AvroProduct> productList, org.joda.time.DateTime processingDate) {
    this.orderCode = orderCode;
    this.customerCode = customerCode;
    this.productList = productList;
    this.processingDate = processingDate;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return orderCode;
    case 1: return customerCode;
    case 2: return productList;
    case 3: return processingDate;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  protected static final org.apache.avro.data.TimeConversions.DateConversion DATE_CONVERSION = new org.apache.avro.data.TimeConversions.DateConversion();
  protected static final org.apache.avro.data.TimeConversions.TimeConversion TIME_CONVERSION = new org.apache.avro.data.TimeConversions.TimeConversion();
  protected static final org.apache.avro.data.TimeConversions.TimestampConversion TIMESTAMP_CONVERSION = new org.apache.avro.data.TimeConversions.TimestampConversion();
  protected static final org.apache.avro.Conversions.DecimalConversion DECIMAL_CONVERSION = new org.apache.avro.Conversions.DecimalConversion();

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      null,
      null,
      TIMESTAMP_CONVERSION,
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: orderCode = (java.lang.String)value$; break;
    case 1: customerCode = (java.lang.String)value$; break;
    case 2: productList = (java.util.List<br.com.retailsales.commons.avro.AvroProduct>)value$; break;
    case 3: processingDate = (org.joda.time.DateTime)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'orderCode' field.
   * @return Order code.
   */
  public java.lang.String getOrderCode() {
    return orderCode;
  }

  /**
   * Sets the value of the 'orderCode' field.
   * Order code.
   * @param value the value to set.
   */
  public void setOrderCode(java.lang.String value) {
    this.orderCode = value;
  }

  /**
   * Gets the value of the 'customerCode' field.
   * @return Customer code ID.
   */
  public java.lang.String getCustomerCode() {
    return customerCode;
  }

  /**
   * Sets the value of the 'customerCode' field.
   * Customer code ID.
   * @param value the value to set.
   */
  public void setCustomerCode(java.lang.String value) {
    this.customerCode = value;
  }

  /**
   * Gets the value of the 'productList' field.
   * @return Product list.
   */
  public java.util.List<br.com.retailsales.commons.avro.AvroProduct> getProductList() {
    return productList;
  }

  /**
   * Sets the value of the 'productList' field.
   * Product list.
   * @param value the value to set.
   */
  public void setProductList(java.util.List<br.com.retailsales.commons.avro.AvroProduct> value) {
    this.productList = value;
  }

  /**
   * Gets the value of the 'processingDate' field.
   * @return The value of the 'processingDate' field.
   */
  public org.joda.time.DateTime getProcessingDate() {
    return processingDate;
  }

  /**
   * Sets the value of the 'processingDate' field.
   * @param value the value to set.
   */
  public void setProcessingDate(org.joda.time.DateTime value) {
    this.processingDate = value;
  }

  /**
   * Creates a new AvroOrder RecordBuilder.
   * @return A new AvroOrder RecordBuilder
   */
  public static br.com.retailsales.commons.avro.AvroOrder.Builder newBuilder() {
    return new br.com.retailsales.commons.avro.AvroOrder.Builder();
  }

  /**
   * Creates a new AvroOrder RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AvroOrder RecordBuilder
   */
  public static br.com.retailsales.commons.avro.AvroOrder.Builder newBuilder(br.com.retailsales.commons.avro.AvroOrder.Builder other) {
    return new br.com.retailsales.commons.avro.AvroOrder.Builder(other);
  }

  /**
   * Creates a new AvroOrder RecordBuilder by copying an existing AvroOrder instance.
   * @param other The existing instance to copy.
   * @return A new AvroOrder RecordBuilder
   */
  public static br.com.retailsales.commons.avro.AvroOrder.Builder newBuilder(br.com.retailsales.commons.avro.AvroOrder other) {
    return new br.com.retailsales.commons.avro.AvroOrder.Builder(other);
  }

  /**
   * RecordBuilder for AvroOrder instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AvroOrder>
    implements org.apache.avro.data.RecordBuilder<AvroOrder> {

    /** Order code. */
    private java.lang.String orderCode;
    /** Customer code ID. */
    private java.lang.String customerCode;
    /** Product list. */
    private java.util.List<br.com.retailsales.commons.avro.AvroProduct> productList;
    private org.joda.time.DateTime processingDate;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(br.com.retailsales.commons.avro.AvroOrder.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.orderCode)) {
        this.orderCode = data().deepCopy(fields()[0].schema(), other.orderCode);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.customerCode)) {
        this.customerCode = data().deepCopy(fields()[1].schema(), other.customerCode);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.productList)) {
        this.productList = data().deepCopy(fields()[2].schema(), other.productList);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.processingDate)) {
        this.processingDate = data().deepCopy(fields()[3].schema(), other.processingDate);
        fieldSetFlags()[3] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing AvroOrder instance
     * @param other The existing instance to copy.
     */
    private Builder(br.com.retailsales.commons.avro.AvroOrder other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.orderCode)) {
        this.orderCode = data().deepCopy(fields()[0].schema(), other.orderCode);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.customerCode)) {
        this.customerCode = data().deepCopy(fields()[1].schema(), other.customerCode);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.productList)) {
        this.productList = data().deepCopy(fields()[2].schema(), other.productList);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.processingDate)) {
        this.processingDate = data().deepCopy(fields()[3].schema(), other.processingDate);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'orderCode' field.
      * Order code.
      * @return The value.
      */
    public java.lang.String getOrderCode() {
      return orderCode;
    }

    /**
      * Sets the value of the 'orderCode' field.
      * Order code.
      * @param value The value of 'orderCode'.
      * @return This builder.
      */
    public br.com.retailsales.commons.avro.AvroOrder.Builder setOrderCode(java.lang.String value) {
      validate(fields()[0], value);
      this.orderCode = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'orderCode' field has been set.
      * Order code.
      * @return True if the 'orderCode' field has been set, false otherwise.
      */
    public boolean hasOrderCode() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'orderCode' field.
      * Order code.
      * @return This builder.
      */
    public br.com.retailsales.commons.avro.AvroOrder.Builder clearOrderCode() {
      orderCode = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'customerCode' field.
      * Customer code ID.
      * @return The value.
      */
    public java.lang.String getCustomerCode() {
      return customerCode;
    }

    /**
      * Sets the value of the 'customerCode' field.
      * Customer code ID.
      * @param value The value of 'customerCode'.
      * @return This builder.
      */
    public br.com.retailsales.commons.avro.AvroOrder.Builder setCustomerCode(java.lang.String value) {
      validate(fields()[1], value);
      this.customerCode = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'customerCode' field has been set.
      * Customer code ID.
      * @return True if the 'customerCode' field has been set, false otherwise.
      */
    public boolean hasCustomerCode() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'customerCode' field.
      * Customer code ID.
      * @return This builder.
      */
    public br.com.retailsales.commons.avro.AvroOrder.Builder clearCustomerCode() {
      customerCode = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'productList' field.
      * Product list.
      * @return The value.
      */
    public java.util.List<br.com.retailsales.commons.avro.AvroProduct> getProductList() {
      return productList;
    }

    /**
      * Sets the value of the 'productList' field.
      * Product list.
      * @param value The value of 'productList'.
      * @return This builder.
      */
    public br.com.retailsales.commons.avro.AvroOrder.Builder setProductList(java.util.List<br.com.retailsales.commons.avro.AvroProduct> value) {
      validate(fields()[2], value);
      this.productList = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'productList' field has been set.
      * Product list.
      * @return True if the 'productList' field has been set, false otherwise.
      */
    public boolean hasProductList() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'productList' field.
      * Product list.
      * @return This builder.
      */
    public br.com.retailsales.commons.avro.AvroOrder.Builder clearProductList() {
      productList = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'processingDate' field.
      * @return The value.
      */
    public org.joda.time.DateTime getProcessingDate() {
      return processingDate;
    }

    /**
      * Sets the value of the 'processingDate' field.
      * @param value The value of 'processingDate'.
      * @return This builder.
      */
    public br.com.retailsales.commons.avro.AvroOrder.Builder setProcessingDate(org.joda.time.DateTime value) {
      validate(fields()[3], value);
      this.processingDate = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'processingDate' field has been set.
      * @return True if the 'processingDate' field has been set, false otherwise.
      */
    public boolean hasProcessingDate() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'processingDate' field.
      * @return This builder.
      */
    public br.com.retailsales.commons.avro.AvroOrder.Builder clearProcessingDate() {
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public AvroOrder build() {
      try {
        AvroOrder record = new AvroOrder();
        record.orderCode = fieldSetFlags()[0] ? this.orderCode : (java.lang.String) defaultValue(fields()[0], record.getConversion(0));
        record.customerCode = fieldSetFlags()[1] ? this.customerCode : (java.lang.String) defaultValue(fields()[1], record.getConversion(1));
        record.productList = fieldSetFlags()[2] ? this.productList : (java.util.List<br.com.retailsales.commons.avro.AvroProduct>) defaultValue(fields()[2], record.getConversion(2));
        record.processingDate = fieldSetFlags()[3] ? this.processingDate : (org.joda.time.DateTime) defaultValue(fields()[3], record.getConversion(3));
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<AvroOrder>
    WRITER$ = (org.apache.avro.io.DatumWriter<AvroOrder>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<AvroOrder>
    READER$ = (org.apache.avro.io.DatumReader<AvroOrder>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
